Client hierarchy rework
tjjfvi/escad pull request #73
Opened 2021-05-01 00:59 UTC by tjjfvi

Fixes #66 
Fixes #29 
Fixes #51

2021-05-07 18:46 UTC, vjjft requested changes

2021-05-07 18:46 UTC, vjjft commented on packages/client/src/HierarchyView/State.ts
> +  ]).concat(str).join("//")
escape `key` or handle using `JSON.stringify`

2021-05-07 18:46 UTC, vjjft commented on packages/client/src/HierarchyView/State.ts
> +  ]).concat(str).join("//")
@vjjft add deferred issue re state representation

2021-05-07 18:46 UTC, vjjft commented on packages/client/src/HierarchyPane.tsx
>    const hierarchy = state.hierarchy()
consider renaming `ClientState.hierarchy` to `renderedHierarchy`

2021-05-11 02:57 UTC, tjjfvi commented on packages/client/src/HierarchyPane.tsx
>    const hierarchy = state.hierarchy()
Not related to this pr, can be considered later

2021-05-11 02:58 UTC, tjjfvi commented on packages/client/src/HierarchyView/State.ts
> +  ]).concat(str).join("//")
Going to leave as-is for now

2021-05-11 02:58 UTC, merged

2021-05-11 14:55 UTC, vjjft commented on packages/client/src/Dropdown.tsx
> +    <select value={key} onChange={event => value(options[event.target.value])}>
```suggestion
export const Dropdown = observer(<T, >({ options, value }: DropdownProps<T>) => {
  const currentValue = value()
  const currentKey = Object.keys(options).find(key => options[key] === currentValue)
  if(!currentKey) throw new Error("Value passed to Dropdown not in options")
  return <div className="Dropdown">
    <select value={currentKey} onChange={event => value(options[event.target.value])}>
```

2021-05-11 14:55 UTC, vjjft commented on packages/client/src/HierarchyView/NestableSpan.tsx
> + * Correctly handles hover & click logic when nested
provide specific description of 'correctly'